# -*- coding: utf-8 -*-
"""Task2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tJFduvhOkimRR8Y1JCQEhMOcxDncN2sc
"""

first_name = input("Enter your first name: ")
last_name = input("Enter your last name: ")
full_name = first_name + " " + last_name
print(f"Hello, {full_name}! Welcome to the Python world.")